export const NEW_QUESTION_REQUEST = "NEW_QUESTION_REQUEST";
export const NEW_QUESTION_SUCCESS = "NEW_QUESTION_SUCCESS";
export const NEW_QUESTION_RESET = "NEW_QUESTION_RESET";
export const NEW_QUESTION_FAIL = "NEW_QUESTION_FAIL";

export const ADMIN_QUESTION_REQUEST = "ADMIN_QUESTION_REQUEST";
export const ADMIN_QUESTION_SUCCESS = "ADMIN_QUESTION_SUCCESS";
export const ADMIN_QUESTION_FAIL = "ADMIN_QUESTION_FAIL";

export const ALL_QUESTION_REQUEST = "ALL_QUESTION_REQUEST";
export const ALL_QUESTION_SUCCESS = "ALL_QUESTION_SUCCESS";
export const ALL_QUESTION_FAIL = "ALL_QUESTION_FAIL";

export const QUESTION_STATS_REQUEST = "QUESTION_STATS_REQUEST";
export const QUESTION_STATS_SUCCESS = "QUESTION_STATS_SUCCESS";
export const QUESTION_STATS_FAIL = "QUESTION_STATS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
