export const NEW_QUIZ_REQUEST = "NEW_QUIZ_REQUEST";
export const NEW_QUIZ_SUCCESS = "NEW_QUIZ_SUCCESS";
export const NEW_QUIZ_RESET = "NEW_QUIZ_RESET";
export const NEW_QUIZ_FAIL = "NEW_QUIZ_FAIL";

export const ALL_QUIZ_REQUEST = "ALL_QUIZ_REQUEST";
export const ALL_QUIZ_SUCCESS = "ALL_QUIZ_SUCCESS";
export const ALL_QUIZ_FAIL = "ALL_QUIZ_FAIL";

export const QUIZ_DETAILS_REQUEST = "QUIZ_DETAILS_REQUEST";
export const QUIZ_DETAILS_SUCCESS = "QUIZ_DETAILS_SUCCESS";
export const QUIZ_DETAILS_FAIL = "QUIZ_DETAILS_FAIL";

export const UPDATE_QUIZ_REQUEST = "UPDATE_QUIZ_REQUEST";
export const UPDATE_QUIZ_SUCCESS = "UPDATE_QUIZ_SUCCESS";
export const UPDATE_QUIZ_RESET = "UPDATE_QUIZ_RESET";
export const UPDATE_QUIZ_FAIL = "UPDATE_QUIZ_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
