export const NEW_RESPONSE_REQUEST = "NEW_RESPONSE_REQUEST";
export const NEW_RESPONSE_SUCCESS = "NEW_RESPONSE_SUCCESS";
export const NEW_RESPONSE_RESET = "NEW_RESPONSE_RESET";
export const NEW_RESPONSE_FAIL = "NEW_RESPONSE_FAIL";

export const ALL_RESPONSE_REQUEST = "ALL_RESPONSE_REQUEST";
export const ALL_RESPONSE_SUCCESS = "ALL_RESPONSE_SUCCESS";
export const ALL_RESPONSE_FAIL = "ALL_RESPONSE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
